// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbz22WzpHAJ2dBFRkUzHBz_YIbqgDBeEE',
    appId: '1:408611194200:web:ea4d9b89f2d3532d20512d',
    messagingSenderId: '408611194200',
    projectId: 'grubbie-101b5',
    authDomain: 'grubbie-101b5.firebaseapp.com',
    storageBucket: 'grubbie-101b5.appspot.com',
    measurementId: 'G-W8W386461P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq1N1DAuf1Ki59NMffyTK7WvNunqx3lHk',
    appId: '1:408611194200:android:43cf583763f2167420512d',
    messagingSenderId: '408611194200',
    projectId: 'grubbie-101b5',
    storageBucket: 'grubbie-101b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRGQNkdvafQmZej3nHZSfDTNb_swVJREA',
    appId: '1:408611194200:ios:6158a0c7a633a69020512d',
    messagingSenderId: '408611194200',
    projectId: 'grubbie-101b5',
    storageBucket: 'grubbie-101b5.appspot.com',
    iosBundleId: 'com.example.grubbie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRGQNkdvafQmZej3nHZSfDTNb_swVJREA',
    appId: '1:408611194200:ios:9fd5110832a5511c20512d',
    messagingSenderId: '408611194200',
    projectId: 'grubbie-101b5',
    storageBucket: 'grubbie-101b5.appspot.com',
    iosBundleId: 'com.example.grubbie.RunnerTests',
  );
}
